esphome:
  name: openandhome
  friendly_name: openandhome

## Fragmente aus dem Beispiel https://github.com/esphome/bluetooth-proxies/blob/main/olimex-esp32-poe-iso.yaml
esp32:
  board: esp32-poe-iso
  framework:
    type: esp-idf

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
##

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "ABCMzxUX4GW+LK8MHT5ThfyiD+vUJaZ7tLBe85eXGJE="

ota:
  password: "5da16f02cac12ba36b9415c899f64d6d"

# AB HIER TEMPERAUR EINSTELLUNGEN

# Nach der offiziellen Anleitung Getting Sensor IDS 
# https://esphome.io/components/sensor/dallas.html#getting-sensor-ids
dallas:
  - pin: GPIO21 # ANPASSEN AUF OLIMEX FREIEN PIN

# Nachdem die Sensor IDS ausgelesen sind:

# sensor:
#   - platform: dallas
#     address: 0xA40000031F055028 # Sensor ID
#     name: "Temperature #1"
#   - platform: dallas
#     address: 0xDD0000031EFB0428 # Sensor ID 
#     name: "Temperature #2"

# ADDITIONAL FEATURES
# Nice to have
# https://bthome.io/ eine Liste mit unterschedlichen BLE Devices die ausgelesen werden können

# esp32_ble_tracker:
#   scan_parameters:
#     interval: 1100ms
#     window: 1100ms
#     active: true

# bluetooth_proxy:
#   active: true
